#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

/**
 * @var ClassLoader $loader
 */
$loader = require 'vendor/autoload.php';

$application = new Application();
$application->addCommands([
  new SiteFactoryAPI\Command\ListBackups(),
  new SiteFactoryAPI\Command\DeleteBackup(),
  new SiteFactoryAPI\Command\ListSites(),
  new SiteFactoryAPI\Command\CreateSite(),
  new SiteFactoryAPI\Command\ListGroups(),
  new SiteFactoryAPI\Command\TrafficMonthly(),
  new SiteFactoryAPI\Command\SiteDomains(),
  new SiteFactoryAPI\Command\SiteFind(),
  new SiteFactoryAPI\Command\SiteInfo(),
  new SiteFactoryAPI\Command\SiteThemeRefresh(),
  new SiteFactoryAPI\Command\TaskStatus(),
]);
$application->run();
